[package]
name = "wasm_hello"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
hex = "0.4.3"
rand = "0.8.5" # because latest version conflicts with ed25519-dalek
wasm-bindgen = "0.2.100"
